# Generated by Django 5.1.2 on 2024-11-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_data_age_delete_wb'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozon',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
