# Generated by Django 5.1.2 on 2024-11-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_data_api_key_ozon_user_data_client_id_ozon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='client_id_ozon',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='count_of_stocks',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
