# Generated by Django 5.1.2 on 2024-11-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_data_client_id_ozon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='api_key_ozon',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
