# Generated by Django 5.1.2 on 2024-11-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_data_api_key_ozon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='count_of_stocks',
            field=models.IntegerField(blank=True),
        ),
    ]
