# Generated by Django 5.1.2 on 2024-11-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_data_count_of_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='identify_of_stock',
            field=models.IntegerField(blank=True, max_length=20),
        ),
    ]
