# Generated by Django 5.1.2 on 2024-11-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_data_identify_of_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='identify_of_stock',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
